import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { describe, expect, test } from 'vitest';

/**
 * Bytecode budget regression test. V8 only inlines a function whose bytecode
 * is under --max-inlined-bytecode-size (460 in Node 24, with 920 cumulative
 * per optimized function), and typed-array field access generates ~3x the
 * bytecode of an object field load — so a hot function that drifts past 460
 * silently stops inlining and costs real time (the original monolithic
 * link() sat at 475 and never inlined; splitting it measured -8..-13% on the
 * propagation shapes; checkDirty at 543 could not inline into run()/
 * computedRead() until its try/finally wrapper and stack growth were split
 * out). Budgets are asserted against the BUILT output (npm test builds
 * first), which is what consumers execute.
 */

const INLINE_LIMIT = 460;

// name -> budget (bytecode bytes). Budgets leave headroom below the V8 limit
// where cheap, and pin exactly the functions on the propagate/read/flush hot
// paths. Raising a budget is a deliberate act: justify it in the PR.
const BUDGETS: Record<string, number> = {
	// graph kernel
	link: 200,
	linkInsert: 340,
	unlink: 300,
	propagate: 420,
	checkDirty: 120, // the walk bracket (held-link release around the entry)
	checkDirtyEntry: 420, // shallow fast paths + the chainCheck dispatch
	chainCheck: 300, // stackless chain walk (not inlined; it loops)
	checkDirtyLoop: INLINE_LIMIT,
	updateAndShallow: 100,
	shallowPropagate: 160,
	isValidLink: 100,
	// The HOST's purge loop (index.ts). 100 -> 120 for hardening 2: the walk
	// re-derives its position from the record after every unlink instead of
	// trusting the unlink's returned next pointer (an unwatched cascade can
	// free links ahead of the walk).
	purgeDeps: 120,
	// the kindless seam + userspace verbs on hot paths
	update: 80, // pure seam trampoline: flags load + hostUpdate dispatch
	notify: 80, // WATCHING dedup + host handoff
};

const pkgRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const smoke = path.join(pkgRoot, 'tests', 'fixtures', 'bytecodeSmoke.mjs');

function measure(): Map<string, number> {
	// NOTE: --print-bytecode-filter takes ONE pattern, not a comma list (a
	// list silently matches nothing) — dump everything and filter here.
	const out = execFileSync(
		process.execPath,
		['--print-bytecode', '--print-bytecode-filter=*', smoke],
		{ cwd: pkgRoot, encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 },
	);
	const sizes = new Map<string, number>();
	let current: string | undefined;
	for (const line of out.split('\n')) {
		const header = /^\[generated bytecode for function: ([A-Za-z_$][\w$]*)/.exec(line);
		if (header) {
			current = header[1];
			continue;
		}
		const len = /^Bytecode length: (\d+)/.exec(line);
		if (len && current !== undefined) {
			// Unrelated functions can share a name (e.g. node internals named
			// `link`); keep the max, which is conservative for the budget.
			sizes.set(current, Math.max(sizes.get(current) ?? 0, Number(len[1])));
			current = undefined;
		}
	}
	return sizes;
}

describe('bytecode budgets (built esm)', () => {
	const sizes = measure();

	test('smoke exercises every budgeted function', () => {
		const missing = Object.keys(BUDGETS).filter((name) => !sizes.has(name));
		expect(missing).toEqual([]);
	});

	for (const [name, budget] of Object.entries(BUDGETS)) {
		test(`${name} <= ${budget}`, () => {
			const size = sizes.get(name);
			expect(size, `bytecode length of ${name}`).toBeDefined();
			expect(size!).toBeLessThanOrEqual(budget);
			expect(budget).toBeLessThanOrEqual(INLINE_LIMIT);
		});
	}
});
